homebrew_packages:
- git
- git-lfs
- mise
- neovim
- uv
- wget
- curl
- xh
- yt-dlp
- fd
- redis
- postgresql@17
- ripgrep
- dockutil

homebrew_cask_packages:
- cleanshot
- betterdisplay
- iterm2
- tailscale-app
- google-chrome

uv_tools:
- name: build
- name: ruff
