if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 13
#ZOXIDE_CMD_OVERRIDE=cd
plugins=(git fzf zoxide mise common-aliases cp docker uv rust pnpm)
[[ "$OSTYPE" == darwin* ]] && plugins+=(macos)
# zsh-you-should-use zsh-autosuggestions
source $ZSH/oh-my-zsh.sh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Environment
export RIPGREP_CONFIG_PATH=~/.config/ripgreprc
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR=vim
elif [[ "$OSTYPE" == darwin* ]]; then
  export EDITOR='code --wait'
else
  export EDITOR=vim
fi

# PATH
export PATH=~/bin:~/pr/github/divadvo-scripts/mac:~/pr/github/divadvo-scripts/mac/pdf:~/.local/bin:~/.cargo/bin:$PATH
[[ "$OSTYPE" == darwin* ]] && export PATH=/opt/homebrew/opt/postgresql@18/bin:$PATH

# Functions
function chpwd_ls { ls }
add-zsh-hook chpwd chpwd_ls

# Aliases
alias zj='zellij attach -c main'
alias zjl='zellij ls'

if [[ "$OSTYPE" == darwin* ]]; then
  alias toggle-dark-mode='osascript -e "tell app \"System Events\" to tell appearance preferences to set dark mode to not dark mode"'
  alias o=open
else
  alias o=xdg-open
fi
