- name: Verify GitHub CLI authentication status
  command: gh auth status
  register: gh_auth_check
  failed_when: gh_auth_check.rc != 0
  changed_when: false

- name: Create main projects directory
  file:
    path: "{{ projects_dir }}"
    state: directory
    mode: '0755'
  become: false

- name: Create priority and recent repository directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ priority_dir }}"
    - "{{ recent_dir }}"

- name: Clone high-priority repositories to {{ priority_dir }}/
  git:
    repo: "git@github.com:{{ item }}.git"
    dest: "{{ priority_dir }}/{{ item.split('/')[1] }}"
    accept_hostkey: yes
  loop: "{{ priority_repos }}"
  retries: 3
  delay: 10
  register: priority_clone_result
  failed_when: priority_clone_result.rc != 0 and "already exists" not in priority_clone_result.msg | default("")

- name: Fetch list of recent repositories from GitHub
  shell: gh repo list --limit {{ max_recent_repos }} --json name,sshUrl --jq '.[] | .sshUrl'
  register: recent_repos_result

# Priority repositories are excluded from recent cloning.
- name: Clone recent repositories to {{ recent_dir }}/ (excluding priority repos)
  git:
    repo: "{{ item }}"
    dest: "{{ recent_dir }}/{{ item.split('/')[-1].replace('.git', '') }}"
    accept_hostkey: yes
  loop: "{{ recent_repos_result.stdout_lines | default([]) }}"
  when: 
    - recent_repos_result is defined 
    - recent_repos_result.stdout_lines is defined
    - item.split('/')[-1].replace('.git', '') not in (priority_repos | map('split', '/') | map('last'))
  retries: 3
  delay: 10
  register: recent_clone_result
  failed_when: recent_clone_result.rc != 0 and "already exists" not in recent_clone_result.msg | default("")

- name: Show summary of cloned repositories
  debug:
    msg: |
      Repository cloning complete!
      
      Priority repositories: {{ priority_repos | length }} repos cloned to {{ priority_dir }}/
      Recent repositories: {{ (recent_repos_result.stdout_lines | default([])) | length }} repos cloned to {{ recent_dir }}/
      
      Check {{ projects_dir }}/ for all your development projects.