- name: Verify GitHub CLI authentication status
  command: gh auth status
  register: gh_auth_check
  failed_when: gh_auth_check.rc != 0
  changed_when: false

- name: Create main projects directory
  file:
    path: "{{ projects_dir }}"
    state: directory
    mode: '0755'
  become: false

- name: Create repository directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ github_dir }}"
    - "{{ github_other_dir }}"
    - "{{ sandbox_dir }}"

- name: Clone priority repositories to {{ github_dir }}/
  command: gh repo clone {{ item }} {{ github_dir }}/{{ item.split('/')[1] }}
  loop: "{{ priority_repos }}"
  register: priority_clone_result
  changed_when: priority_clone_result.rc == 0 and "already exists" not in priority_clone_result.stderr
  failed_when: priority_clone_result.rc != 0 and "already exists" not in priority_clone_result.stderr

- name: Fetch list of recent repositories from GitHub
  shell: gh repo list --limit {{ max_recent_repos }} --json nameWithOwner --jq '.[] | .nameWithOwner'
  register: recent_repos_result

# Clone remaining recent repositories (excluding already cloned priority repos)
- name: Clone recent repositories to {{ github_dir }}/ (excluding priority repos)
  command: gh repo clone {{ item }} {{ github_dir }}/{{ item.split('/')[1] }}
  loop: "{{ recent_repos_result.stdout_lines | default([]) }}"
  when: 
    - recent_repos_result is defined 
    - recent_repos_result.stdout_lines is defined
    - item not in priority_repos
  register: recent_clone_result
  changed_when: recent_clone_result.rc == 0 and "already exists" not in recent_clone_result.stderr
  failed_when: recent_clone_result.rc != 0 and "already exists" not in recent_clone_result.stderr

- name: Show summary of cloned repositories
  debug:
    msg: |
      Repository cloning complete!
      
      Your repositories: {{ priority_repos | length }} priority + {{ (recent_repos_result.stdout_lines | default([]) | reject('in', priority_repos) | list) | length }} recent repos cloned to {{ github_dir }}/
      
      Directory structure:
      - {{ github_dir }}/ - Your personal repositories
      - {{ github_other_dir }}/ - External repositories (empty, ready for use)
      - {{ sandbox_dir }}/ - Experimental projects (empty, ready for use)
      
      Check {{ projects_dir }}/ for all your development projects.