- name: Verify GitHub CLI authentication status
  command: gh auth status
  register: gh_auth_check
  failed_when: gh_auth_check.rc != 0
  changed_when: false

- name: Create main projects directory
  file:
    path: "{{ projects_dir }}"
    state: directory
    mode: '0755'
  become: false

- name: Create priority and recent repository directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ priority_dir }}"
    - "{{ recent_dir }}"

- name: Clone high-priority repositories to {{ priority_dir }}/
  command: gh repo clone {{ item }} {{ priority_dir }}/{{ item.split('/')[1] }}
  loop: "{{ priority_repos }}"
  register: priority_clone_result
  changed_when: priority_clone_result.rc == 0 and "already exists" not in priority_clone_result.stderr
  failed_when: priority_clone_result.rc != 0 and "already exists" not in priority_clone_result.stderr

- name: Fetch list of recent repositories from GitHub
  shell: gh repo list --limit {{ max_recent_repos }} --json nameWithOwner --jq '.[] | .nameWithOwner'
  register: recent_repos_result

# Priority repositories are excluded from recent cloning.
- name: Clone recent repositories to {{ recent_dir }}/ (excluding priority repos)
  command: gh repo clone {{ item }} {{ recent_dir }}/{{ item.split('/')[1] }}
  loop: "{{ recent_repos_result.stdout_lines | default([]) }}"
  when: 
    - recent_repos_result is defined 
    - recent_repos_result.stdout_lines is defined
    - item not in priority_repos
  register: recent_clone_result
  changed_when: recent_clone_result.rc == 0 and "already exists" not in recent_clone_result.stderr
  failed_when: recent_clone_result.rc != 0 and "already exists" not in recent_clone_result.stderr

- name: Show summary of cloned repositories
  debug:
    msg: |
      Repository cloning complete!
      
      Priority repositories: {{ priority_repos | length }} repos cloned to {{ priority_dir }}/
      Recent repositories: {{ (recent_repos_result.stdout_lines | default([])) | length }} repos cloned to {{ recent_dir }}/
      
      Check {{ projects_dir }}/ for all your development projects.